# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lokaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalenavn', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=5)),
                ('slut', models.CharField(max_length=5)),
                ('pre_break', models.IntegerField(default=15)),
                ('post_break', models.IntegerField(default=15)),
                ('actid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Lokaler')),
            ],
        ),
        migrations.CreateModel(
            name='Øvedag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radmd5', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lokaler',
            name='øvedag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Øvedag'),
        ),
    ]
