# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenter',
            name='lokale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Lokaler'),
        ),
        migrations.AlterField(
            model_name='segmenter',
            name='actid',
            field=models.IntegerField(default=0),
        ),
    ]
