# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160311_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Øvedag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField(verbose_name='Øvedag')),
                ('radmd5', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lokaler',
            name='ovedag',
        ),
        migrations.DeleteModel(
            name='Ovedag',
        ),
        migrations.AddField(
            model_name='lokaler',
            name='øvedag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Øvedag'),
        ),
    ]
