# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160311_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Øvedag',
            new_name='Øvedage',
        ),
    ]
