# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_øvedage_radmd5'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAD_verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5chksum', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
