# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_rad_verifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenter',
            name='slut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='segmenter',
            name='start',
            field=models.TimeField(),
        ),
    ]
