# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20160312_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='øvedage',
            name='dato',
            field=models.DateField(unique=True),
        ),
    ]
